"""
app/services/candidate_service.py
─────────────────────────────────
Service layer for persisting and retrieving candidate records in MongoDB.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from app.database import get_resume_collection
from app.models.resume import CandidateRecord, EvaluationResult, ParsedResume


async def save_candidate_evaluation(
    job_description: str,
    parsed: ParsedResume,
    eval_result: EvaluationResult,
) -> str:
    """
    Constructs a CandidateRecord and saves it to MongoDB.

    Parameters
    ----------
    job_description : str
        The raw job description used for the evaluation.
    parsed : ParsedResume
        The structured resume data extracted by the LLM.
    eval_result : EvaluationResult
        The scoring output generated by the LLM.

    Returns
    -------
    str
        The unique ID of the inserted candidate record.
    """
    # Generate a unique string ID (UUIDv4)
    record_id = str(uuid.uuid4())
    
    # Construct the full CandidateRecord
    record = CandidateRecord(
        id=record_id,
        job_description=job_description,
        parsed_resume=parsed,
        evaluation=eval_result,
        created_at=datetime.now(timezone.utc),
    )
    
    # Insert into MongoDB
    collection = get_resume_collection()
    
    # Motor/PyMongo requires a dictionary.
    # We use model_dump() and map the id to _id so MongoDB uses it as the primary key.
    document = record.model_dump(mode="json")
    document["_id"] = document.pop("id")
    
    await collection.insert_one(document)
    
    return record_id


async def list_shortlisted_candidates(min_score: float = 0.0) -> list[dict]:
    """
    Retrieves a list of candidates from MongoDB that meet or exceed the min_score.

    Parameters
    ----------
    min_score : float, optional
        The minimum match score required, by default 0.0.

    Returns
    -------
    list[dict]
        A list of serialized CandidateRecord dictionaries, sorted by score descending.
    """
    collection = get_resume_collection()
    
    # Query for records where evaluation.match_score >= min_score
    query = {"evaluation.match_score": {"$gte": min_score}}
    
    # Sort descending by evaluation.match_score
    cursor = collection.find(query).sort("evaluation.match_score", -1)
    
    results = []
    async for document in cursor:
        # Map MongoDB's _id back to id for the response
        document["id"] = document.pop("_id")
        results.append(document)
        
    return results
